version: '3'

services:
  item-app:
    image: item-app
    container_name: item-app
    restart: always
    depends_on:
      - item-db
    ports:
      - "80:8080"
    networks:
      - app-network
  item-db:
    image: mongo:3
    container_name: item-db
    restart: always
    volumes:
      - app-db:/data/db
    networks:
      - app-network

volumes:
  app-db:

networks:
  app-network: